added files homework 3: Task1-Task8
Bahdanau/homework_task_java pull request #3
Opened 2023-02-07 14:03 UTC by Bahdanau

2023-02-13 13:13 UTC, Willynick requested changes

2023-02-13 13:13 UTC, Willynick commented on src/by/itacademy/courses/hw3/Task1.java
> +        int number6 = number3;
Переменные number6 и number7 не используются

2023-02-13 13:13 UTC, Willynick commented on src/by/itacademy/courses/hw3/Task3.java
> +        dayWeek = dayWeek;
А зачем мы присваиваем перемнной dayWeek саму же себя?

2023-02-13 13:13 UTC, Willynick commented on src/by/itacademy/courses/hw3/Task6.java
> +        System.out.println("Введите сторону треугольника №1: ");
Что-то с логикой работы
![image](https://user-images.githubusercontent.com/57830441/218466953-51146d40-dfb4-4249-a71d-4670b1856b98.png)

2023-02-13 13:13 UTC, Willynick commented on src/by/itacademy/courses/hw3/Task6.java
> +            if (long2 <= long1 + long3) {
Везде по коду, где строчка кода if (long2 <= long1 + long3)
одинаковые куски кода присутствуют.

А одинаковые куски коды мы всегда выносим в отдельные методы)

2023-02-13 13:13 UTC, Willynick commented on src/by/itacademy/courses/hw3/Task6.java
> +            if (long2 <= long1 + long3) {
И просто в месте, где это необходимо, вызываем нужный нам метод

2023-02-13 13:13 UTC, Willynick commented on src/by/itacademy/courses/hw3/Task8.java
> +        Scanner in = new Scanner(System.in);
Ниразу не используется переменная in

2023-02-14 05:57 UTC, Bahdanau commented on src/by/itacademy/courses/hw3/Task6.java
> +        System.out.println("Введите сторону треугольника №1: ");
тут понял <=поставил  а надо было <

2023-02-14 05:58 UTC, Bahdanau commented on src/by/itacademy/courses/hw3/Task6.java
> +            if (long2 <= long1 + long3) {
понял как проще сделать можно )

2023-02-14 11:58 UTC, Willynick requested changes

2023-02-14 11:58 UTC, Willynick commented on src/by/itacademy/courses/hw3/Task3.java
> +            case 6, 7:
Не уверен, что так можно. Лучше
case 6:
case 7:

2023-02-14 11:58 UTC, Willynick commented on src/by/itacademy/courses/hw3/Task5.java
> +            if (number >= 0 && number < 15) {
Так как выполняется выше if - то number всегда будет больше 0. Избыточное условие

2023-02-14 11:58 UTC, Willynick commented on src/by/itacademy/courses/hw3/Task5.java
> +            } else if (number >= 15 && number < 30) {
Тоже самое, у нас здесь по любому будет >=15. Условие избыточное. В остальных else if блоках - также

2023-02-14 11:58 UTC, Willynick commented on src/by/itacademy/courses/hw3/Task8.java
> +import java.util.Scanner;
Не забываем удалять неиспользуемые importы

2023-02-14 12:41 UTC, Bahdanau commented on src/by/itacademy/courses/hw3/Task3.java
> +            case 6, 7:
я конечно исправлю но работает)

2023-02-18 14:01 UTC, Willynick commented
У тебя сюда попали файлы из 4-ой домашки, посмотри пожалуйста

2023-02-18 14:46 UTC, Bahdanau commented
все удалил, не понял как они туда попали

2023-02-20 11:56 UTC, Willynick commented
> все удалил, не понял как они туда попали

У тебя ещё там старые изменения из второй домашки есть. Попробуй замержить ветку task-2 в ветку task-3

2023-02-20 12:07 UTC, Bahdanau commented
не мержиться

2023-02-20 12:13 UTC, Bahdanau commented
ну я снова что то удалил

2023-02-22 12:37 UTC, merged