Task 4
Bahdanau/homework_task_java pull request #4
Opened 2023-02-12 18:38 UTC by Bahdanau

2023-02-20 12:07 UTC, Willynick requested changes

2023-02-20 12:07 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task4.java
> +        for (int i = 0; i < myArray.length; i++) {
Очень хорошее решение задачи с циклом. Молодец!!!

2023-02-20 12:07 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task5.java
> +            if (i % 2 != 0) {
Можно аналогичную операцию интерпретировать и запихнуть в for.
Например i=i+2 вместо i++

2023-02-20 12:07 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task5.java
> +        int indexOfMax = 0;
Эта переменная никогда не используется

2023-02-20 12:07 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task7.java
> +            myArray1[i] = (int) (Math.random() * (20 - 0) + 0);
20 - 0 = 20
Можно сразу так и написать)
+ 0 тоже не совсем понятно для чего

2023-02-20 13:56 UTC, Bahdanau commented on src/by/itacademy/courses/hw4/Task1.java
> +        mulTabl = mulTabl;
Согласен, видимо не доглядел и оставил

2023-02-20 13:57 UTC, Bahdanau commented on src/by/itacademy/courses/hw4/Task4.java
> +        for (int i = 0; i < myArray.length; i++) {
Спасибо)!!!

2023-02-20 13:57 UTC, Bahdanau commented on src/by/itacademy/courses/hw4/Task5.java
> +            if (i % 2 != 0) {
Согласен, с этим for нужно меньше циклов сделать

2023-02-20 13:58 UTC, Bahdanau commented on src/by/itacademy/courses/hw4/Task5.java
> +        int indexOfMax = 0;
Согласен, убрана

2023-02-20 14:02 UTC, Bahdanau commented on src/by/itacademy/courses/hw4/Task7.java
> +            myArray1[i] = (int) (Math.random() * (20 - 0) + 0);
Привычка с одной темы 
Генерация случайного вещественного числа из промежутка [a;b):
 (Math.random() * (b-a)  + a);
вот и писал целиком

2023-02-22 12:40 UTC, Willynick requested changes

2023-02-22 12:40 UTC, Willynick commented on src/by/itacademy/courses/hw4/Task5.java
> +            if (i % 2 != 0) {
У тебя есть i = i + 2. Цикл у тебя будет идти и так по четным, поэтому нет необходимости в проверке i % 2
Только i = 0 нужно сделать

2023-02-23 05:56 UTC, Bahdanau commented on src/by/itacademy/courses/hw4/Task5.java
> +            if (i % 2 != 0) {
убрал

2023-03-02 11:59 UTC, merged